"""Create User table

Revision ID: 345cc5f61358
Revises: 
Create Date: 2021-08-14 19:01:18.785149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345cc5f61358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('avg_ticket', sa.Numeric(), nullable=True),
    sa.Column('last_ticket', sa.Numeric(), nullable=True),
    sa.Column('most_frequent_store_cnpj', sa.String(), nullable=True),
    sa.Column('last_store_cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
